### ISSUE TITLE
Does the vcsr support vertex insertion ? If not, how could i implement it

### ISSUE THREAD

**Issue by Yongze-zzz** [DIR-LAB/VCSR#2]
Hello author, does your insert function of VCSR data structure only support inserting edges that source vertices existing in the base graph, or my question is, how do they support vertex inserting?

**Comment by Yongze-zzz** [comment]
Does the assertion influence the insert operation, I implement another data structure based on the vcsr,but the assertion happened [here](https://github.com/DIR-LAB/VCSR/blob/7c004d115197eab0002b641290616addc4569124/vcsr/src/graph.h#L806)

**Comment by biqar** [comment]
Dear [Yongze](https://github.com/Yongze-zzz), Thanks for your query. Currently, VCSR expects to know the max vertex-id upfront and accepts vertex insertion only during the initialization. That means, while initializing VCSR, it creates the vertex array based on the max vertex-id (i.e., MAX_VERTEX) found in the base graph. Therefore, if your dynamic graph has an edge with vertex-id larger than MAX_VERTEX, VCSR needs to perform a rebuild. Unfortunately, we have not yet provided the necessary function for this rebuild operation.

So, one way to solve this problem is to put an edge with the largest vertex-id in your graph in the base graph input. Otherwise, you can request the function rebuilding VCSR once you want to increase the MAX_VERTEX limit. However, the later process will be a bit slow, and we do not expect it to happen frequently.

**Comment by Yongze-zzz** [comment]
Ok, Thanks!
By the way,Could I adjust the density of vcsr sot that every segment has little blank space ?

**Comment by biqar** [comment]
Yes, you can change the value of [up_0 here](https://github.com/DIR-LAB/VCSR/blob/7c004d115197eab0002b641290616addc4569124/vcsr/src/graph.h#L887). Currently the value is set as `1.00` meaning the rebalance will be triggered when the segment is full. Feel free to change this value and let me know if you face any difficulty.

**Comment by Yongze-zzz** [comment]
thank u. It does work. In your paper ,you said the edge delete operation is "Specifically, for deleted edges, we will place a tombstone to it by changing its src field to be an invalid negative number and return without reclaiming the space."  My implementation is to perform a binary search on the edge corresponding to src in the segment, and then set the position to 0. Is this the correct implementation?

**Comment by biqar** [comment]
@Yongze-zzz, I think there are a couple of things that you need to consider. I assume you want to delete an edge `<src, dst>`?
1. One way of deleting this edge is to add an edge by adding the negation of destination vertex-id (i.e., `<src, -dst>`). Therefore, you need to handle this case in the edge iterator or graph analysis. For example, in PageRank, you need to update the algorithm to handle the deleted edge while calculating the PageRank score. Particularly, in [line 49 of PageRank algorithm](https://github.com/DIR-LAB/VCSR/blob/7c004d115197eab0002b641290616addc4569124/vcsr/src/pr.cc#L49), you will need to handle negative neighboring vertex-ids as a deleted edge (e.g., adding `incoming_total -= outgoing_contrib[-v];` for negative neighboring edges).
2. Another way of deleting this edge is what you mentioned in your comment (e.g., by performing a binary search on the edge array corresponding to src in the segment and then setting the position to 0). However, to perform a binary search in the edge array, you will need to know the timestamp of the edge (`<src, dst>`) that was added before, as we store the adjacent edges of a vertex based on the arrival time, not the destination vertex-ids. Even if you delete edges this way, you will need to update the edge iterator or graph analysis to skip these deleted edges (mentioned earlier). Furthermore, a compaction method might be helpful to reclaim the space of the deleted edges as well (which is not implemented in this current version).

Feel free to let us know, if you need any further support in this direction.

**Comment by biqar** [comment]
@Yongze-zzz, please let us know if we can close this issue. Thanks.
